#!/usr/bin/env sh

help() {
    echo "Usage          $0 -h | [-d] <flask-command> <flask-args>"
    echo "-h             show this help"
    echo "-d    --dev    set the environment to development and debug to true for the given flask command"
    exit
}

export FLASK_APP=api
export FLASK_DEBUG=0
export FLASK_ENV=production

for i in "$@"
do
    case $i in
    -h)
    help
    ;;
    -d|--dev)
    FLASK_DEBUG=1
    FLASK_ENV=development
    shift
    ;;
    esac
done

flask "$1"
