"""Add order column to station model

Revision ID: 0f3b86567b26
Revises: 23b7424a4e18
Create Date: 2021-11-13 20:04:56.333843+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0f3b86567b26"
down_revision = "23b7424a4e18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stations", sa.Column("order", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stations", "order")
    # ### end Alembic commands ###
