"""Change Description length

Revision ID: 1ffd1a52fe93
Revises: 3547e8c9e19d
Create Date: 2021-11-03 19:26:10.780075+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ffd1a52fe93'
down_revision = '3547e8c9e19d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_sources', 'description',
               existing_type=sa.VARCHAR(length=900),
               type_=sa.String(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_sources', 'description',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=900),
               existing_nullable=True)
    # ### end Alembic commands ###
