"""Update Fields to Species and datasources

Revision ID: 23b7424a4e18
Revises: 2567fffa963f
Create Date: 2021-11-11 19:02:02.157165+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "23b7424a4e18"
down_revision = "2567fffa963f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_sources", sa.Column("title_short", sa.String(length=150), nullable=False)
    )
    op.add_column("data_sources", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "data_sources", sa.Column("curation", sa.String(length=90), nullable=False)
    )
    op.add_column(
        "data_sources", sa.Column("record_count", sa.Integer(), nullable=True)
    )
    op.add_column("data_sources", sa.Column("updated_at", sa.Date(), nullable=False))
    op.add_column(
        "data_sources", sa.Column("is_out_link_ready", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "data_sources", sa.Column("home_url", sa.String(length=200), nullable=True)
    )
    op.add_column(
        "data_sources", sa.Column("url_template", sa.String(length=200), nullable=True)
    )

    op.add_column("species", sa.Column("outlink", sa.String(length=300), nullable=True))
    op.alter_column(
        "species",
        "current_record_id",
        existing_type=sa.VARCHAR(length=300),
        nullable=True,
    )
    op.drop_index("idx_stations_coordinates", table_name="stations")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_stations_coordinates", "stations", ["coordinates"], unique=False
    )
    op.alter_column(
        "species",
        "current_record_id",
        existing_type=sa.VARCHAR(length=300),
        nullable=False,
    )
    op.drop_column("species", "outlink")
    op.drop_column("data_sources", "url_template")
    op.drop_column("data_sources", "home_url")
    op.drop_column("data_sources", "is_out_link_ready")
    op.drop_column("data_sources", "updated_at")
    op.drop_column("data_sources", "record_count")
    op.drop_column("data_sources", "curation")
    op.drop_column("data_sources", "description")
    op.drop_column("data_sources", "title_short")
    # ### end Alembic commands ###
