"""Add order column to station model

Revision ID: 0d064aa10422
Revises: 47e9177640b3
Create Date: 2021-11-06 22:56:51.819298+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0d064aa10422"
down_revision = "47e9177640b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "species",
        "current_record_id",
        existing_type=sa.VARCHAR(length=300),
        nullable=True,
    )
    op.add_column("stations", sa.Column("order", sa.Integer(), nullable=True))
    op.drop_index("idx_stations_coordinates", table_name="stations")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_stations_coordinates", "stations", ["coordinates"], unique=False
    )
    op.drop_column("stations", "order")
    op.alter_column(
        "species",
        "current_record_id",
        existing_type=sa.VARCHAR(length=300),
        nullable=False,
    )
    # ### end Alembic commands ###
