"""Creating Migrations

Revision ID: 3547e8c9e19d
Revises: 234e66ef24b7
Create Date: 2021-11-02 19:59:17.919078+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3547e8c9e19d'
down_revision = '234e66ef24b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('outlink', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'outlink')
    # ### end Alembic commands ###
