"""Add Stations, Species, and DataSource models

Revision ID: 47e9177640b3
Revises: 73a4f6b274b7
Create Date: 2021-09-02 16:03:25.453792+00:00

"""
import sqlalchemy as sa

from alembic import op
from app.utils.db import Geometry

# revision identifiers, used by Alembic.
revision = "47e9177640b3"
down_revision = "73a4f6b274b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_data_sources_id"), "data_sources", ["id"], unique=False)
    op.create_index(
        op.f("ix_data_sources_title"), "data_sources", ["title"], unique=False
    )
    op.create_table(
        "stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.Column("sediment_sample", sa.String(length=50), nullable=True),
        sa.Column(
            "coordinates",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("water_body", sa.String(length=200), nullable=False),
        sa.Column("sea_area", sa.String(length=200), nullable=True),
        sa.Column("place", sa.String(length=200), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("fao_area", sa.Integer(), nullable=False),
        sa.Column("gear", sa.String(length=50), nullable=True),
        sa.Column("depth_fathoms", sa.Integer(), nullable=True),
        sa.Column("bottom_water_temp_c", sa.Float(), nullable=True),
        sa.Column("bottom_water_depth_fathoms", sa.Integer(), nullable=True),
        sa.Column("specific_gravity_at_bottom", sa.Float(), nullable=True),
        sa.Column("surface_temp_c", sa.Float(), nullable=True),
        sa.Column("specific_gravity_at_surface", sa.Float(), nullable=True),
        sa.Column("water_temp_c_at_depth_fathoms", sa.JSON(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stations_id"), "stations", ["id"], unique=False)
    op.create_table(
        "species",
        sa.Column("id", sa.String(length=300), nullable=False),
        sa.Column("matched_name", sa.String(length=300), nullable=False),
        sa.Column(
            "matched_canonical_simple_name", sa.String(length=300), nullable=True
        ),
        sa.Column("matched_canonical_full_name", sa.String(length=300), nullable=True),
        sa.Column("common_name", sa.String(length=300), nullable=True),
        sa.Column("classification_path", sa.String(length=800)),
        sa.Column("classification_ranks", sa.String(length=800)),
        sa.Column("classification_ids", sa.String(length=800)),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_species_id"), "species", ["id"], unique=False)
    op.create_table(
        "stations_species",
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("species_id", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(
            ["species_id"],
            ["species.id"],
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
        ),
        sa.PrimaryKeyConstraint("station_id", "species_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stations_species")
    op.drop_index(op.f("ix_species_id"), table_name="species")
    op.drop_table("species")
    op.drop_index(op.f("ix_stations_id"), table_name="stations")
    op.drop_table("stations")
    op.drop_index(op.f("ix_data_sources_title"), table_name="data_sources")
    op.drop_index(op.f("ix_data_sources_id"), table_name="data_sources")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
