"""Change Description length

Revision ID: 02aca791d88a
Revises: 5f37b194b830
Create Date: 2021-11-03 19:30:43.488527+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02aca791d88a'
down_revision = '5f37b194b830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_sources', 'description',
               existing_type=sa.VARCHAR(length=3000),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_sources', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=True)
    # ### end Alembic commands ###
