"""Ad Default Values for Non Nullable Fields

Revision ID: bcb13c126197
Revises: 02aca791d88a
Create Date: 2021-11-08 22:46:50.382666+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb13c126197'
down_revision = '02aca791d88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
