name: Perform Type and Formatting checks on a new/edited pull requests.

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited]

jobs:
  perfrom-type-and-formatting-check:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install python requirements
        run: |
          pip install -U pip
          pip install poetry
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Run type and format checking scripts
        run: |
          poetry run ./scripts/lint.sh
